Introduce SetUnmarshalErrorAction in the beanstalk worker
tomponline/beanstalkworker pull request #27
Opened 2018-12-01 23:26 UTC by NevilleC

**Original issue:** https://github.com/tomponline/beanstalkworker/issues/26

If there is an unmarshal error in the worker,

https://github.com/tomponline/beanstalkworker/blob/f880af6af406bae85607cffb56c63e34cc3b0ab9/beanstalkworker/worker.go#L61
```go
		if err := json.Unmarshal(*job.body, dataPtr.Interface()); err != nil {
			job.LogError("Error decoding JSON for job: ", err, ", '", string(*job.body), "', releasing...")
			job.Release()
			return
		}
```
the job is released by default. This is not ideal as the job can entry an infinity loop. The user might want the job to be buried or deleted in such case.

The goal of this PR is to introduce a new method for the worker, called `SetUnmarshalErrorAction`, that could let the user decide which action to take (delete, bury or release as the default choice). In order to accomplish that, the worker struct has a new field `unmarshalErrorAction` that will remember the user choice.

Then, the job struct can apply the user's decision if a unmarshal error appears via the new method `unmarshalErrorAction`.

The `beanstalkworker_demo.go` has been updated with an example.

**Manual testing**:

Using a worker without using the `SetUnmarshalErrorAction`:
```
Error: Error decoding JSON for job: json: cannot unmarshal number into Go value of type string, 'job data..., Release...
```
It's released as this is the default behaviour.

With 
```diff
        // initializing bsWorker
        bsWorker := beanstalkworker.NewWorker(*beanstalkd)
-
+       bsWorker.SetUnmarshalErrorAction(beanstalkworker.ActionDeleteJob)
```
:
```
Error: Error decoding JSON for job: json: cannot unmarshal number into Go value of type string, job data, Delete...
```
It's deleted (I checked manually)

With
```diff
        // initializing bsWorker
        bsWorker := beanstalkworker.NewWorker(*beanstalkd)
-
+       bsWorker.SetUnmarshalErrorAction(beanstalkworker.ActionBuryJob)
```
: 
```
Error: Error decoding JSON for job: json: cannot unmarshal number into Go value of type string, '{"igrp":19,"rowId":"545247","callDatetime":"2018-11-30 09:15:32"}#015#012', Bury...
```

It's bury (checked manually as well)

2018-12-01 23:31 UTC, NevilleC commented
@tomponline @gha May I have a review, please?

2018-12-02 07:22 UTC, tomponline commented on beanstalkworker/rawJob.go
> +	ActionDeleteJob  = "Delete"
@NevilleC can these be made so they dont start with upper case first letters, such that the error log shows this:

```
Error decoding JSON for job: ", err, ", '"{}"', release...
```

2018-12-02 07:24 UTC, tomponline requested changes
Thanks @NevilleC this is great work. Thanks for cleaning the other parts up too.

Can you make that small change to the casing of the action codes such that they dont have upper case first in the middle of the logging sentence, and then I'll merge.

Thanks

2018-12-02 17:07 UTC, NevilleC commented on beanstalkworker/rawJob.go
> +	ActionDeleteJob  = "Delete"
@tomponline Thanks for the review. Agreed. This should be fixed now. It was an oversight, my bad.

2018-12-02 20:52 UTC, tomponline approved these changes
thanks @NevilleC

2018-12-02 20:52 UTC, merged